groups:
- name: demo.rules
  rules:
  - alert: OpenShiftApiserverDown
    expr: absent(up{job="apiserver"} == 1)
    for: 30s
    labels:
      severity: critical
    annotations:
      description: No API servers are reachable or all have disappeared from service
        discovery
  - alert: OpenShiftApiserverDown
    expr: absent(up{job="apiserver"} == 1)
    for: 1m
    labels:
      severity: page
    annotations:
      description: No API servers are reachable or all have disappeared from service
        discovery
